##### LIBRARY #####

library(shiny)
library(magick)
library(shinyjs)
library(httr)
library(DBI)
library(RPostgreSQL)
library(yaml)
library(tools)



##### SERVER DEFINITION #####

shinyServer(function(input, output, session) {

              onStop(function(){
                       if (exists("sql_con")){
                         dbDisconnect(sql_con)
                       }
                       if (file.exists("tmp.jpg")){
                         file.remove("tmp.jpg")
                       }
                       print("Session disconnected")
                       print("=====================")
              })

  creds <<- read_yaml(Sys.getenv("CREDS_PATH"))


  sql_connect <- function(creds){
    dbConnect(dbDriver("PostgreSQL"),
              host=as.character(creds$pg_host),
              user=as.character(creds$pg_user),
              password=as.character(creds$pg_pw),
              dbname="novartis_dummy_db"
    )
  }


  pull_raw_data <- function(){
    sql_con <- sql_connect(creds)
    raw_data <- dbGetQuery(sql_con,statement="SELECT * FROM pulled_images WHERE file_name LIKE '%_raw%'")
    dbDisconnect(sql_con)

    return(raw_data)
  }

  pull_thumb_data <- function(){
    sql_con <- sql_connect(creds)
    thumb_data <- dbGetQuery(sql_con,statement="SELECT * FROM pulled_images WHERE file_name LIKE '%_thumbnail%'")
    dbDisconnect(sql_con)

    return(thumb_data)
  }

 pull_all_data <- function(){
    sql_con <- sql_connect(creds)
    all_data <- dbGetQuery(sql_con,statement="SELECT DISTINCT * FROM pulled_images")
    dbDisconnect(sql_con)

    return(all_data)
  }

 get_image_path <- function(image_id, type){
   image_path <- full_dat$file_path[which(full_dat$image_id == image_id & grepl(pattern = type, x = full_dat$file_path) == TRUE)]
   return(as.character(image_path))

 }

 cache_raw <- function(image_id){
   return(image_read(get_image_path(image_id, "raw")))
 }

 get_conv <- function(image_id, type){
   return(full_dat$raw_conv_fctr[which(full_dat$image_id == image_id & grepl(pattern = type, x = full_dat$file_path) == TRUE)])
 }

 get_crop_string <- function(brush_info, conv){
   ## Dividing the preview by the conv will get us the raw value (conv was generated by multiplying raw by conv)
   width <- (brush_info$xmax-brush_info$xmin)/conv
   height <- (brush_info$ymax-brush_info$ymin)/conv
   xoffset <- brush_info$xmin/conv
   yoffset <- brush_info$ymin/conv

   return(paste(width,"x",height,"+",xoffset,"+",yoffset, sep=""))
 }

 zoom_gen <- function(crop_string){
   image_crop(raw_image, crop_string) %>%
     image_write("tmp.jpg")
 }

 get_all_info <- function(image_id, raw_pointer){
   preview_path <- get_image_path(image_id, "preview")
   prev_im_info <- image_info(image_read(preview_path))
   raw_im_info <- image_info(raw_pointer)

   out <- list(preview = list(dims = paste("Preview size: ", prev_im_info$width, "x", prev_im_info$height, " pixels", sep=""),
                              path = paste("File Location: ", preview_path, sep="")),
               raw = list(dims = paste("Raw size: ", raw_im_info$width, "x", raw_im_info$height, " pixels", sep=""),
                           path = paste("File Location: ", get_image_path(image_id, "raw"), sep=""))
               )
   return(out)
 }
 update_sidebar <- function(){renderUI({
      HTML(paste(paste("<b>",sidebar_info$preview$dims,"</b>"),
                 paste("<b>",sidebar_info$raw$dims,"</b>"),
                 sep="<br/>"
                           )
      )
 })
 }


 full_dat <<- pull_all_data()
 image_id <<- full_dat$image_id[1]
 raw_image <<- cache_raw(image_id)
 sidebar_info <<- get_all_info(image_id, raw_image)

    output$sidebar <- renderUI({
      selectInput(inputId = "file_select",
                  label = "Choose a file",
                  selected = NULL,
                  choices = unique(full_dat$image_id)
      )
    })

    output$image_info <- renderUI({list(
      tags$h4("Image Info"),
      uiOutput("image_dims")
            )
    })

    output$image_dims <- update_sidebar()

    output$mainPage <- renderUI({list(
     tags$h3("Image Preview"),
     imageOutput("thumb_preview",
                 click = "thumb_click",
                 brush = brushOpts(id = "thumb_brush")
     )
   )})

   observeEvent(input$file_select,{

                  image_id <<- input$file_select

                  output$mainPage <- renderUI({list(
                    tags$h3("Image Preview"),
                    imageOutput("thumb_preview",
                                click = "thumb_click",
                                brush = brushOpts(id = "thumb_brush")
                    )
                    )})

                  raw_image <<- cache_raw(image_id)
                  sidebar_info <<- get_all_info(image_id, raw_image)

                  output$image_dims <- update_sidebar()

                  output$thumb_preview <- renderImage({
                    list(src = get_image_path(image_id, "preview"))
                  }, deleteFile=FALSE)

   })

   observeEvent(input$thumb_brush,{
                  brush <<- reactiveVal(input$thumb_brush)
                  crop_string <- get_crop_string(brush(),get_conv(image_id, "preview"))
                  zoom_gen(crop_string)

                  output$mainPage <- renderUI({list(
                                                    tags$h3("Image Preview"),
                                                    imageOutput("thumb_preview",
                                                                height = "100%",
                                                                click = "thumb_click",
                                                                brush = brushOpts(
                                                                                  id = "thumb_brush"
                                                                        )
                                                                ),
                                                    tags$h3("Zoom"),
                                                    imageOutput("zoom_preview",
                                                                height = "100%",
                                                                width = "100%"
                                                                )

                    )
                    })

                  output$zoom_preview <- renderImage({
                    list(src = "tmp.jpg")
                         }, deleteFile=FALSE)
   })

   output$thumb_preview <- renderImage({
     list(src = get_image_path(image_id, "preview"))
   }, deleteFile=FALSE)
})

